name: Daily Discord Bot Run

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
# permissions to allow the workflow to read the contents of the repository
permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: yarn ts-node src/index.ts
